Rails.application.routes.draw do

  devise_for :users
  root to: 'trainings#index'


  # get 'profiles/new'
  # get 'profiles/create'
  # get 'profiles/update'
  # get 'profiles/edit'
  # get 'profiles/destroy'
  # get 'profiles/index'
  # get 'profiles/show'
  # get 'products/new'
  # get 'products/create'
  # get 'products/update'
  # get 'products/edit'
  # get 'products/destroy'
  # get 'products/index'
  # get 'products/show'
  # get 'trainings/new'
  # get 'trainings/create'
  # get 'trainings/update'
  # get 'trainings/edit'
  # get 'trainings/destroy'
  # get 'trainings/index'
  # get 'trainings/show'
  # get 'lectures/new'
  # get 'lectures/create'
  # get 'lectures/update'
  # get 'lectures/edit'
  # get 'lectures/destroy'
  # get 'lectures/index'
  # get 'lectures/show'
  # get 'roles/new'
  # get 'roles/create'
  # get 'roles/update'
  # get 'roles/edit'
  # get 'roles/destroy'
  # get 'roles/index'
  # get 'roles/show'
  # get 'entreprises/new'
  # get 'entreprises/create'
  # get 'entreprises/update'
  # get 'entreprises/edit'
  # get 'entreprises/destroy'
  # get 'entreprises/index'
  # get 'entreprises/show'
  # get 'users/new'
  # get 'users/create'
  # get 'users/update'
  # get 'users/edit'
  # get 'users/destroy'
  # get 'users/index'
  # get 'users/show'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
